name: image_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
repository: https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 1.2.1
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=3.38.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: image_picker_android
      ios:
        default_package: image_picker_ios
      linux:
        default_package: image_picker_linux
      macos:
        default_package: image_picker_macos
      web:
        default_package: image_picker_for_web
      windows:
        default_package: image_picker_windows

dependencies:
  flutter:
    sdk: flutter
  image_picker_android:
    git: https://github.com/kumsumit/image_picker_android.git
  image_picker_for_web:
    git: https://github.com/kumsumit/image_picker_for_web.git
  image_picker_ios:
    git: https://github.com/kumsumit/image_picker_ios.git
  image_picker_linux:
    git: https://github.com/kumsumit/image_picker_linux.git
  image_picker_macos:
    git: https://github.com/kumsumit/image_picker_macos.git  
  image_picker_platform_interface:
    git: https://github.com/kumsumit/image_picker_platform_interface.git
  image_picker_windows: 
    git: https://github.com/kumsumit/image_picker_windows.git

dev_dependencies:
  build_runner: ^2.1.10
  cross_file: ^0.3.5 # Mockito generates a direct include.
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

topics:
  - camera
  - image-picker
  - files
  - file-selection
